apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: us-east-1a.fs-4eefca07.efs.us-east-1.amazonaws.com
    path: "/"
