kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik
rules:
- apiGroups: ["","extensions"]
  resources: ["configmaps","secrets","services","endpoints","ingresses","nodes","pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create"]
- apiGroups: ["extensions",""]
  resources: ["ingresses","ingresses/status"]
  verbs: ["get","update","create","list","patch","delete","watch"]
- apiGroups: ["*",""]
  resources: ["events","certificates","secrets"]
  verbs: ["get","update","create","list","patch","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: default
